### ISSUE TITLE
prismaOrderBy error when 2 or more fields selected for ordering 

### ISSUE THREAD

**Issue by ccfiel** [hayes/pothos#1016]
The query will error if you select 2 or more fields for ordering. It's fine when you select one field. I am using MongoDB. Do you have any idea why?

The Code
```
const ItemOrderBy: InputRef<Prisma.itemsOrderByWithRelationInput> =
  builder.prismaOrderBy('items', {
    fields: () => ({
      id: true,
      category: true,
      name: true,
      createdAt: true,
    }),
  });

builder.queryField('getItems', (t) =>
  t.prismaField({
    type: ['items'],
    authScopes: {
      isAuthenticated: true,
    },
    args: {
      order: t.arg({ type: ItemOrderBy }),
    },
    nullable: true,
    resolve: async (query, root, args, context) => {
      const result = await db.items.findMany({
        where: {
          userId: { equals: context?.currentUser?.userId as string },
        },
        orderBy: args.order ?? undefined,
      });
      return result;
    },
  })
);


```

The Query
```
query MyQuery {
  getItems(orderBy: {name: Asc, category: Asc}) {
    barcode
    cost
    name
    modifiedAt
  }
}
```

The Error
```
  156 },
  157 nullable: true,
  158 resolve: async (query, root, args, context) => {
→ 159   const result = await db.items.findMany({
          where: {
            userId: {
              equals: "hUptwpzLiZY8GKocyZTiCbORrCF3"
            }
          },
          orderBy: {
            category: "asc",
            name: "asc"
          }
          ~~~~~~~~~~~~~~~~~
        })

Argument `orderBy`: Invalid value provided. Expected itemsOrderByWithRelationInput[], provided Object.
    at xn (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:116:5852)
    at vn.handleRequestError (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:123:6429)
    at vn.handleAndLogRequestError (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:123:5839)
    at l (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:128:9763) {
  path: [ 'getItems' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
```

I also tried to change it to an array.

```
    args: {
      order: t.arg({ type: [ItemOrderBy] }),
    },
```

But I got a different error.

```
  157 },
  158 nullable: true,
  159 resolve: async (query, root, args, context) => {
→ 160   const result = await db.items.findMany({
          where: {
            userId: {
              equals: "hUptwpzLiZY8GKocyZTiCbORrCF3"
            }
          },
          orderBy: [
            {
              category: "asc",
              name: "asc"
            }
          ],
          ~~~~~~~~~~~~~~~~~~~
          take: undefined
        })

Argument `orderBy`: Invalid value provided. Expected itemsOrderByWithRelationInput, provided (Object).
    at xn (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:116:5852)
    at vn.handleRequestError (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:123:6429)
    at vn.handleAndLogRequestError (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:123:5839)
    at l (/Users/chrisianfiel/Projects/graphql-server/node_modules/@prisma/client/runtime/library.js:128:9763) {
  path: [ 'getItems' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
}
```

**Comment by hayes** [comment]
making it an array should work, but you need to pass your orderBy as separate objects:

`orderBy: [{ category: "asc" }, {  name: "asc" }]`

**Comment by ccfiel** [comment]
@hayes thanks! What do you mean by passing my orderBy as separate objects? By the way, I tried the sample code above. It works, but I need to use the args variable so that it would be dynamic.

**Comment by hayes** [comment]
You made the graphql argument a list, but it looks like you only passed one object into the list with multiple properties.  You need to write your query with a list of objects for the order by with only 1 property per object

**Comment by ccfiel** [comment]
@hayes Thanks! For reference for others, I have changed the query like this.
```
query MyQuery {
  getItems(orderBy: [{ category: Asc }, {  name: Asc }]) {
    category
    cost
    name
  }
}
```
