### ISSUE TITLE
Prisma relationCount: Cannot return null for non-nullable field

### ISSUE THREAD

**Issue by kelly-ry4n** [hayes/pothos#1054]
Hi! I'm having a runtime error counting relations with `t.relationCount`.

I have a schema like this

```prisma

model ProjectDataset {
  id                      String           @id @unique @default(uuid())
  LabelDataset            LabelDataset[]
}

model LabelDataset {
  id               String         @id @unique @default(uuid())
  projectDataset   ProjectDataset @relation(fields: [projectDatasetId], references: [id])
  projectDatasetId String
}
```

and then:

```javascript

builder.prismaObject('ProjectDataset', {
  fields: t => ({
    id: t.exposeID('id'),
    totalLabels: t.relationCount('LabelDataset'),
})

builder.queryField('projectDataset', t =>
  t.prismaFieldWithInput({
    input: {
      projectDataSetId: t.input.string({ required: true }),
    },
    type: 'ProjectDataset',
    resolve: async (_query, _parent, args, context, _info) => {
      return await prisma.projectDataset.findFirstOrThrow({
          where: {id: args.input.projectDatasetId}
      })
    },
  }),
);

```

throws a runtime 

```
Error: Cannot return null for non-nullable field ProjectDataset.totalLabels.
    at executeField (/Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:337:25)
    at executeFields (/Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:271:28)
    at collectAndExecuteSubfields (/Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:686:23)
    at completeObjectValue (/Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:676:12)
    at completeValue (/Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:445:16)
    at completeValue (/Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:419:27)
    at /Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/execute.js:334:49
    at /Users/kelly/projects/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
    at async Promise.all (index 0) {
  path: [ 'projectDataset', 'totalLabels' ],
  locations: [ { line: 6, column: 5 } ],
  extensions: [Object: null prototype] {}
}

```
 This is actually happening for a few similar fields in my project.

Any ideas? So far I've worked around by implementing as an int field, but would love to have the relationCount working.

**Comment by hayes** [comment]
The issue is that you aren't properly spreading the query argument into you Prisma call

**Comment by hayes** [comment]
If you don't use the query argument all your queries will much less efficient, and some things won't work correctly

**Comment by kelly-ry4n** [comment]
Amazing, I'll make sure to do that everywhere, don't know how missed it.

Thanks so much for the help @hayes !

Fix was:

```diff

builder.queryField('projectDataset', t =>
  t.prismaFieldWithInput({
    input: {
      projectDataSetId: t.input.string({ required: true }),
    },
    type: 'ProjectDataset',
-    resolve: async (_query, _parent, args, context, _info) => {
+    resolve: async (query, _parent, args, context, _info) => {
      return await prisma.projectDataset.findFirstOrThrow({
+          ...query
          where: {id: args.input.projectDatasetId}
      })
    },
  }),
);
```
