### ISSUE TITLE
error `node_modules/@pothos/core/esm/build-cache.js (506:22) @ eval` in 3.37

### ISSUE THREAD

**Issue by Enalmada** [hayes/pothos#1056]
When updating to 3.37.0 I started getting this `node_modules/@pothos/core/esm/build-cache.js (506:22) @ eval`.  No other code has changed and going back to 3.36.0 works.
```
 ⨯ node_modules/@pothos/core/esm/build-cache.js (506:22) @ eval
 ⨯ PothosError: No plugin named withInput was registered
    at eval (webpack-internal:///(rsc)/./node_modules/@pothos/core/esm/build-cache.js:514:23)
    at Array.map (<anonymous>)
    at new BuildCache (webpack-internal:///(rsc)/./node_modules/@pothos/core/esm/build-cache.js:511:162)
    at SchemaBuilder.toSchema (webpack-internal:///(rsc)/./node_modules/@pothos/core/esm/builder.js:352:28)
    at eval (webpack-internal:///(rsc)/./src/server/graphql/schema.ts:13:77)
    at (rsc)/./src/server/graphql/schema.ts (/home/enalm/code/t3-challenge-wsl/.next/server/app/api/graphql/route.js:454:1)
    at __webpack_require__ (/home/enalm/code/t3-challenge-wsl/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/server/graphql/yoga.ts:6:80)
    at (rsc)/./src/server/graphql/yoga.ts (/home/enalm/code/t3-challenge-wsl/.next/server/app/api/graphql/route.js:476:1)
    at __webpack_require__ (/home/enalm/code/t3-challenge-wsl/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/api/graphql/route.ts:17:78)
    at (rsc)/./src/app/api/graphql/route.ts (/home/enalm/code/t3-challenge-wsl/.next/server/app/api/graphql/route.js:333:1)
    at __webpack_require__ (/home/enalm/code/t3-challenge-wsl/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fgraphql%2Froute&page=%2Fapi%2Fgraphql%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fgraphql%2Froute.ts&appDir=%2Fhome%2Fenalm%2Fcode%2Ft3-challenge-wsl%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fenalm%2Fcode%2Ft3-challenge-wsl&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=standalone&preferredRegion=&middlewareConfig=e30%3D!:16:120)
```

Is there something that might have changed in code or requirements to cause this?  I believe I am loading WithInputPlugin as [docs](https://pothos-graphql.dev/docs/plugins/with-input) state.
```
import SchemaBuilder from '@pothos/core';
import WithInputPlugin from '@pothos/plugin-with-input';
import { DateTimeResolver, JSONResolver, NonEmptyStringResolver } from 'graphql-scalars';

export interface SchemaTypes {
  Scalars: {
    DateTime: {
      Input: Date;
      Output: Date;
    };
    JSON: {
      Input: unknown;
      Output: unknown;
    };
    NonEmptyString: {
      Input: string;
      Output: string;
    };
  };
  Context: MyContextType;
}

export const builder = new SchemaBuilder<SchemaTypes>({
  plugins: [WithInputPlugin]
});
```

**Comment by hayes** [comment]
Nothing related to plugins changed in that version.  Are you sure that Pothos was the only dependency that you changed?

**Comment by Enalmada** [comment]
I didn't see anything stand out to me in the changes of pothos either but I am pretty sure it is updating to that version which is causing it.   I do also seem to need to delete my node_modules directory when I revert back to 3.36 to get everything working again.  That is unusual and I am unsure why. 

Here is the project which I am trying to update to 3.37 as reproduction:  https://github.com/Enalmada/nextjs-boilerplate (develop branch).   There is alot going on in that project and I can make a smaller reproduction if it doesn't help.  I would also like to show off how pothos is used to start a new project along side other technologies so I also welcome anything you would recommend done differently.

**Comment by hayes** [comment]
Thanks for the link.  Manually updating pothos in package.json and then running bun install reproduces the issue.

This is related to how bun updates dependencies.  @pothos/plugin-with-input depends on @pothos/core@3.36.0, so when you update to 3.37.0, bun adds a copy of 3.36.0 in node_modules nested inside @pothos/plugin-with-input which is where the plugin gets registed.  Basically when you update with bun, you end up with multiple copies of pothos, which is the root cause of the issue here.

you can get around this with `bun remove @pothos/plugin-with-input && bun add @pothos/plugin-with-input`

**Comment by Enalmada** [comment]
Thanks @hayes for your help with this.  That underlying issues doesn't sound good but your solution does work.  Something I will be more careful about while playing around with bun.

**Comment by hayes** [comment]
opened an issue here: https://github.com/oven-sh/bun/issues/6085
