### ISSUE TITLE
Prisma plugin failing to read datamodel

### ISSUE THREAD

**Issue by jasonkuhrt** [hayes/pothos#1147]
In a Prisma+Pothos+CloudFlare Worker context the following error happens at boot.

```
✘ [ERROR] service core:user:control-plane-development: Uncaught TypeError: Cannot read properties of undefined (reading 'datamodel')

    at null.<anonymous> (index.js:118526:322) in getDMMF
    at null.<anonymous> (index.js:119596:205) in schemaBuilderProto.prismaObject
    at null.<anonymous> (index.js:120126:25)
```

Prisma Client is being generated with `--no-engine` but I wouldn't think that matters? (`"prisma generate --no-engine"`).

We are using edge client, does that matter?

![CleanShot 2024-01-31 at 15 27 52@2x](https://github.com/hayes/pothos/assets/284476/986dfd5c-fadd-4c5d-9e83-11df58024f5e)

I could try to create a smaller repro of this issue, but, maybe its obvious to someone already?

**Comment by jasonkuhrt** [comment]
We were a few versions behind on Prisma, updating seems to have made this error go away. In some places we were importing from edge (`@prisma/client/edge`), and some places just the root (`@prisma/client`). That might have been the issue...
