### ISSUE TITLE
Unable to run prisma examples

### ISSUE THREAD

**Issue by fcanela** [hayes/pothos#406]
Hello. Any tips to run the prisma examples?

I performed `pnpm install`. After that I tried to use `pnpm generate` but I get the following error:

```
$ pnpm generate

> @pothos-examples/prisma@2.0.5 generate /home/fcanela/downloads/repo/pothos/examples/prisma
> prisma generate

Prisma schema loaded from prisma/schema.prisma
Error: Generator at prisma-pothos-types could not start:

node:internal/modules/cjs/loader:942
  throw err;
  ^
Error: Cannot find module '../lib/generator.js'
Require stack:
- /home/fcanela/downloads/repo/pothos/packages/plugin-prisma/bin/generator.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/fcanela/downloads/repo/pothos/packages/plugin-prisma/bin/generator.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/fcanela/downloads/repo/pothos/packages/plugin-prisma/bin/generator.js'
  ]
}
Node.js v18.2.0
```

If I try to start it directly, it also fails (make sense as I've skipped the previous step):

```
$ pnpm start

> @pothos-examples/prisma@2.0.5 start /home/fcanela/downloads/repo/pothos/examples/prisma
> node -r @swc-node/register src/server.ts

node:internal/modules/cjs/loader:489
      throw e;
      ^

Error: Cannot find module '/home/fcanela/downloads/repo/pothos/examples/prisma/node_modules/@pothos/core/lib/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:483:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/fcanela/downloads/repo/pothos/examples/prisma/src/builder.ts:1:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/fcanela/downloads/repo/pothos/examples/prisma/node_modules/@pothos/core/package.json'
}

Node.js v18.2.0
 ELIFECYCLE  Command failed with exit code 1.
```

Any tips on how are you running it? Do I need to use an specific Node version or something?

**Comment by hayes** [comment]
Sorry, this got lost in my notifications.  I think you just need to build the plugin first.   Easiest option is probably just to run pnpm ci, which will get everything built and run tests to make sure it's all working

**Comment by hayes** [comment]
Let me know if you have any more issues, going to close this for now
