### ISSUE TITLE
Apollo subgraph compatibility

### ISSUE THREAD

**Issue by trevor-scheer** [hayes/pothos#453]
Hey there, Trevor from Apollo! We noticed you have federation support via plugin. Would you be interested in joining our list of subgraph compatible libraries? Would love to see you listed in our docs.

We have a repo [here](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/CONTRIBUTORS.md
) (pointing you to the relevant setup guide) which will run compatibility tests against your library and update [our docs](https://www.apollographql.com/docs/federation/other-servers) accordingly.

Thanks!

**Comment by hayes** [comment]
Hey! Would be great to get pothos added.  I'll try to find some time this weekend on getting that set up.

**Comment by trevor-scheer** [comment]
Great, bug me if you need anything!

**Comment by hayes** [comment]
@trevor-scheer having a hard time finding docs on what the @tag directive does

**Comment by hayes** [comment]
nevermind, found it here: https://specs.apollo.dev/tag/v0.2/

**Comment by hayes** [comment]
@trevor-scheer Having issues getting started in the apollo-federation-subgraph-compatibility repo.

It looks like there is an image I don't have access to:  

```
Starting containers...
Error: Command failed with exit code 18: docker compose -f docker-compose.yaml -f /Users/michaelhayes/code/apollo-federation-subgraph-compatibility/implementations/pothos/docker-compose.yaml up --build --detach
users Pulling
inventory Pulling
inventory Error
users Error
Error response from daemon: pull access denied for apollo-federation-implementations/inventory, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
    at makeError (/Users/michaelhayes/code/apollo-federation-subgraph-compatibility/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/michaelhayes/code/apollo-federation-subgraph-compatibility/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runDockerCompose (/Users/michaelhayes/code/apollo-federation-subgraph-compatibility/dist/index.js:47:5)
    at async main (/Users/michaelhayes/code/apollo-federation-subgraph-compatibility/dist/index.js:72:35) {
  shortMessage: 'Command failed with exit code 18: docker compose -f docker-compose.yaml -f /Users/michaelhayes/code/apollo-federation-subgraph-compatibility/implementations/pothos/docker-compose.yaml up --build --detach',
  command: 'docker compose -f docker-compose.yaml -f /Users/michaelhayes/code/apollo-federation-subgraph-compatibility/implementations/pothos/docker-compose.yaml up --build --detach',
  escapedCommand: 'docker compose -f docker-compose.yaml -f "/Users/michaelhayes/code/apollo-federation-subgraph-compatibility/implementations/pothos/docker-compose.yaml" up --build --detach',
  exitCode: 18,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'users Pulling \n' +
    'inventory Pulling \n' +
    'inventory Error \n' +
    'users Error \n' +
    "Error response from daemon: pull access denied for apollo-federation-implementations/inventory, repository does not exist or may require 'docker login': denied: requested access to the resource is denied",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by trevor-scheer** [comment]
Hey @hayes, looking into this now - I can't pull it myself with the same error. I'll follow up when I have more info. Sorry for the trouble!

**Comment by hayes** [comment]
Made some progress, you need to run `npm run setup` or `docker:inventory` to get past that.

**Comment by hayes** [comment]
@trevor-scheer got a PR up here: https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/124
