### ISSUE TITLE
Cannot Generate Client Types using Method from the Docs

### ISSUE THREAD

**Issue by GV14982** [hayes/pothos#604]
Hi there, I'm trying to generate client code using graphql-codegen. I used the method outlined in the docs here: https://pothos-graphql.dev/docs/guide/generating-client-types but I keep getting the following error: 
```
> graphql-codegen

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate schema.graphql
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ schema.graphql
    Failed to load schema from src/graphql/build-schema.js:

        Unable to load from file "/Users/gvqz/dev/github/aww-rats/web-client/apps/backtalk/src/graphql/build-schema.js": Error: Ref [object Object
] has not been implemented
    at ConfigStore.onTypeConfig (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@po
thos/core/lib/config-store.js:190:19)
    at ConfigStore.addFieldRef (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@pot
hos/core/lib/config-store.js:74:18)
    at PrismaObjectFieldBuilder.createField (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node
_modules/@pothos/core/lib/fieldUtils/base.js:22:34)
    at PrismaObjectFieldBuilder.field (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modul
es/@pothos/core/lib/fieldUtils/root.js:141:21)
    at fields (/Users/gvqz/dev/github/aww-rats/web-client/apps/backtalk/src/graphql/schema.ts:38:17)
    at Object.objectType.fields (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+plugin-prisma@3.34.0_ke7gbmcdmxcvezhzp5wgvv
5u6m/node_modules/@pothos/plugin-prisma/lib/schema-builder.js:83:30)
    at /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@pothos/core/lib/builder.js:1
09:32
    at /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@pothos/core/lib/config-store
.js:240:74
    at ConfigStore.onTypeConfig (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@po
thos/core/lib/config-store.js:186:13)
    at ConfigStore.addFields (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@potho
s/core/lib/config-store.js:239:18)
        Error: Unable to load from file "/Users/gvqz/dev/github/aww-rats/web-client/apps/backtalk/src/graphql/build-schema.js": Error: Ref [object
 Object] has not been implemented
    at ConfigStore.onTypeConfig (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@po
thos/core/lib/config-store.js:190:19)
    at ConfigStore.addFieldRef (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@pot
hos/core/lib/config-store.js:74:18)
    at PrismaObjectFieldBuilder.createField (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node
_modules/@pothos/core/lib/fieldUtils/base.js:22:34)
    at PrismaObjectFieldBuilder.field (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modul
es/@pothos/core/lib/fieldUtils/root.js:141:21)
    at fields (/Users/gvqz/dev/github/aww-rats/web-client/apps/backtalk/src/graphql/schema.ts:38:17)
    at Object.objectType.fields (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+plugin-prisma@3.34.0_ke7gbmcdmxcvezhzp5wgvv
5u6m/node_modules/@pothos/plugin-prisma/lib/schema-builder.js:83:30)
    at /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@pothos/core/lib/builder.js:1
09:32
    at /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@pothos/core/lib/config-store
.js:240:74
    at ConfigStore.onTypeConfig (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@po
thos/core/lib/config-store.js:186:13)
    at ConfigStore.addFields (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@pothos+core@3.21.0_graphql@15.8.0/node_modules/@potho
s/core/lib/config-store.js:239:18)
    at tryToLoadFromExport (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+code-file-loader@7.2.14_graphql@15.8.0/no
de_modules/@graphql-tools/code-file-loader/index.js:148:15)
    at async CodeFileLoader.handleSinglePath (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+code-file-loader@7.2.14
_graphql@15.8.0/node_modules/@graphql-tools/code-file-loader/index.js:328:32)
    at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+code-file-loader@7.2.14_graphql@15.8.0/node_modules/@gra
phql-tools/code-file-loader/index.js:252:32
    at async Promise.all (index 0)
    at async CodeFileLoader.load (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+code-file-loader@7.2.14_graphql@15.
8.0/node_modules/@graphql-tools/code-file-loader/index.js:250:9)
    at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+load@7.5.10_graphql@15.8.0/node_modules/@graphql-tools/l
oad/index.js:75:39
    at async Promise.all (index 0)
    at async loadFile (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+load@7.5.10_graphql@15.8.0/node_modules/@graph
ql-tools/load/index.js:73:9)
    at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-tools+load@7.5.10_graphql@15.8.0/node_modules/@graphql-tools/l
oad/index.js:386:25

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
    Error: Failed to load schema
        at loadSchema (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_mo
dules/@graphql-codegen/cli/bin.js:509:15)
        at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_modules/
@graphql-codegen/cli/bin.js:1039:65
        at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_modules/
@graphql-codegen/cli/bin.js:1038:52
        at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_modules/
@graphql-codegen/cli/bin.js:925:21
    Error: Failed to load schema
        at loadSchema (/Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_mo
dules/@graphql-codegen/cli/bin.js:509:15)
        at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_modules/
@graphql-codegen/cli/bin.js:1039:65
        at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_modules/
@graphql-codegen/cli/bin.js:1038:52
        at async /Users/gvqz/dev/github/aww-rats/web-client/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_arnf6cwz5d6dhgritfmehxtbju/node_modules/
@graphql-codegen/cli/bin.js:925:21
```

I am using the prisma plugin, here is my schema.ts:
```typescript
import SchemaBuilder from '@pothos/core';
import { PrismaClient, Role, Price_Tier } from '@prisma/client';
import PrismaPlugin from '@pothos/plugin-prisma';
// This is the default location for the generator, but this can be
// customized as described above.
// Using a type only import will help avoid issues with undeclared
// exports in esm mode
import PrismaTypes from '@pothos/plugin-prisma/generated';

const prisma = new PrismaClient({});

const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes;
}>({
  plugins: [PrismaPlugin],
  prisma: {
    client: prisma,
  }, 
});

builder.prismaObject('User', {
  fields: (t) => ({
    wallet: t.exposeID('wallet'),
    profile: t.relation('profile', {nullable: true}),
    team_users: t.relation('team_user'),
    survey_responses: t.relation('survey_responses'),
  })
});

builder.prismaObject('Profile', {
  fields: (t) => ({
    wallet: t.exposeID('wallet'),
    username: t.exposeString('username', {nullable: true}),
    name: t.exposeString('name', {nullable: true}),
    email: t.exposeString('email', {nullable: true}),
    user: t.relation('user'),
  })
})

builder.prismaObject('Team_User', {
  fields: (t) => ({
    wallet: t.exposeID('wallet'),
    team_id: t.exposeID('team_id'),
    role: t.field({
      type: Role,
      resolve: (parent) => parent.role
    }),
    user: t.relation('user'),
    team: t.relation('team'),
  })
})

builder.prismaObject('Team', {
  fields: (t) => ({
    id: t.exposeID('id'),
    name: t.exposeString('name'),
    tier: t.field({
      type: Price_Tier,
      resolve: (parent) => parent.tier
    }),
    team_users: t.relation('team_user'),
  })
})

builder.queryType({
  fields: t => ({
    users: t.prismaField({
      type: ['User'],
      resolve: (query) => prisma.user.findMany({
        ...query,
      })
    }),
    user: t.prismaField({
      type: 'User',
      resolve: (query, _parent, {wallet}) => prisma.user.findUniqueOrThrow({
        ...query,
        where: {wallet: wallet ?? undefined}
      }),
      args: {
        wallet: t.arg({
          type: 'String',
          required: false,
        })
      }
    })
  })
})

export const schema = builder.toSchema();
```

and my build-schema.js:
```javascript
module.exports = require('@boost/module').requireModule(require.resolve('./schema.ts'));
```

I am at a bit of a loss, and I was wondering if anyone had any ideas I could try. Thanks!

**Comment by hayes** [comment]
This error should probably be better, but I think the issue is you are defining the `survey_responses` relation without implementing the corresponding type

**Comment by GV14982** [comment]
Ah, wonderful! Thanks for the tip.
