### ISSUE TITLE
Implementing Smart Subscription plugin results in `Ref Subscription has not been implemented`

### ISSUE THREAD

**Issue by felixhaeberle** [hayes/pothos#609]
Hello again :)

I'm currently exploring around subscriptions and have installed the smart subscription plugin, and integrated it like this:

```ts
export const builder = new SchemaBuilder<{ PrismaTypes: PrismaTypes; Context: GraphQLContext; DefaultFieldNullability: true }>({
  defaultFieldNullability: true,
  plugins: [PrismaPlugin, RelayPlugin, SmartSubscriptionsPlugin],
  relayOptions: {},
  prisma: {
    client: prisma,
  },
  smartSubscriptions: {
    ...subscribeOptionsFromIterator((name, { pubsub }) => {
      return pubsub.asyncIterator(name);
    }),
  },
});
```

Now, I want to use the subscriptions in my queries like this:
```ts
builder.queryField('user', (t) =>
  t.prismaField({
    type: 'User',
    args: {
      alias: t.arg.string(),
    },
    smartSubscription: true,
    resolve: async (query, root, { alias }, ctx) => {
      if (!alias) {
        throw new Error(
          "Please provide an user alias to the user query"
        );
      }

      return prisma.user.findUnique({
        ...query,
        where: { alias: alias },
      })
    }
  }),
);

builder.queryField('getValidAlias', (t) =>
  t.prismaField({
    type: 'User',
    args: {
      alias: t.arg.string(),
    },
    smartSubscription: true,
    resolve: async (query, root, { alias }, ctx) => {
      if (!alias) {
        throw new Error(
          "Please provide an user alias to the user query"
        );
      }

      return prisma.user.findUnique({
        where: { alias: alias },
      })
    }
  }),
);
```

In my imagination this would create two subscribtions on the Subscriptions type, but instead, this gives the following error when hitting the API:

```bash
error - Error: Ref Subscription has not been implemented
    at ConfigStore.onTypeConfig (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/config-store.js:190:19)
    at ConfigStore.addFields (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/config-store.js:239:18)
    at SchemaBuilder.subscriptionField (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/builder.js:199:26)
    at PothosSmartSubscriptionsPlugin.onOutputFieldConfig (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/plugin-smart-subscriptions/lib/index.js:97:26)
    at /Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/plugins/merge-plugins.js:18:93
    at Array.reduceRight (<anonymous>)
    at MergedPlugins.onOutputFieldConfig (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/plugins/merge-plugins.js:18:29)
    at BuildCache.buildFields (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/build-cache.js:163:73)
    at BuildCache.getRootFields (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/build-cache.js:248:21)
    at BuildCache.getFields (/Users/felixhaberle/Desktop/git/homeofopensource/node_modules/@pothos/core/lib/build-cache.js:253:29)
event - build page: /next/dist/pages/_error
```

I'm pretty new to how subscriptions work in graphql and managed to create a Apollo Server + WebSocket API with Nextjs with the help of [this example ](https://github.com/vercel/next.js/discussions/27680#discussioncomment-3105268). What am I doing wrong here?

**Comment by hayes** [comment]
Just need to define the subscription type: `builder.subscriptionType({})`

**Comment by felixhaeberle** [comment]
Thanks very much!! This was the fix.

**Comment by nylon22** [comment]
FWIW - I ran into the same issue with mutations:

```
Error: Ref Mutation has not been implemented
```

Similarly, the fix was to set the mutation type: `builder.mutationType({})`

**Comment by hyusetiawan** [comment]
conceptually, {mutation|query|subscription}Type({}) creates that high level type, after that you would do {mutation|query|subscription}{field|fields} to add fields into each of the type accordingly, so:
```
builder.queryType({})
builder.queryField('newQuery', {})
```
