### ISSUE TITLE
Upgrade to Next 13: `TypeError: (0 , _graphql.getArgumentValues) is not a function`

### ISSUE THREAD

**Issue by felixhaeberle** [hayes/pothos#693]
Hey, there – thank you for doing an amazin job with this library.

I upgraded to Next.js 13 an got this error:

I use Pothos in conjunction with Recoil where I store the data and the fetches are handled through urql.
Maybe this information helps you a bit. I can provide more if needed.

```json
{
   "errors":[
      {
         "message":"(0 , _graphql.getArgumentValues) is not a function",
         "locations":[
            {
               "line":2,
               "column":3
            }
         ],
         "path":[
            "currentUser"
         ],
         "extensions":{
            "code":"INTERNAL_SERVER_ERROR",
            "exception":{
               "stacktrace":[
                  "TypeError: (0 , _graphql.getArgumentValues) is not a function",
                  "    at addFieldSelection (/Users/felixhaberle/Desktop/git/backstage/node_modules/@pothos/plugin-prisma/lib/util/map-query.js:123:53)",
                  "    at addNestedSelections (/Users/felixhaberle/Desktop/git/backstage/node_modules/@pothos/plugin-prisma/lib/util/map-query.js:91:17)",
                  "    at addTypeSelectionsForField (/Users/felixhaberle/Desktop/git/backstage/node_modules/@pothos/plugin-prisma/lib/util/map-query.js:47:9)",
                  "    at queryFromInfo (/Users/felixhaberle/Desktop/git/backstage/node_modules/@pothos/plugin-prisma/lib/util/map-query.js:197:9)",
                  "    at resolve (/Users/felixhaberle/Desktop/git/backstage/node_modules/@pothos/plugin-prisma/lib/field-builder.js:33:55)",
                  "    at field.resolve (/Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:56:26)",
                  "    at resolveField (/Users/felixhaberle/Desktop/git/backstage/node_modules/graphql/execution/execute.js:464:18)",
                  "    at executeFields (/Users/felixhaberle/Desktop/git/backstage/node_modules/graphql/execution/execute.js:292:18)",
                  "    at executeOperation (/Users/felixhaberle/Desktop/git/backstage/node_modules/graphql/execution/execute.js:236:122)",
                  "    at executeImpl (/Users/felixhaberle/Desktop/git/backstage/node_modules/graphql/execution/execute.js:116:14)",
                  "    at execute (/Users/felixhaberle/Desktop/git/backstage/node_modules/graphql/execution/execute.js:60:35)",
                  "    at execute (/Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)",
                  "    at processGraphQLRequest (/Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-core/dist/requestPipeline.js:148:34)",
                  "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                  "    at async processHTTPRequest (/Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)",
                  "    at async graphqlHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-micro/dist/microApollo.js:31:55)",
                  "    at async ApolloServer.handleGraphqlRequestsWithServer (/Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-micro/dist/ApolloServer.js:87:34)",
                  "    at async /Users/felixhaberle/Desktop/git/backstage/node_modules/apollo-server-micro/dist/ApolloServer.js:30:21"
               ]
            }
         }
      }
   ],
   "data":{
      "currentUser":null
   }
}
```

For example, this is the fetching part:
```jsx
import { atom, selector } from "recoil";

import { client } from "../graphql/client";
import { GetCurrentUserDocument } from "../graphql/getCurrentUser.generated";
import { User } from "../graphql/types.generated";

// fetch user data from the server
export const currentUserFetch = selector<User | null>({
  key: "currentUserFetch",
  get: async ({ get }) => {
    try {
      const response = await client.query(GetCurrentUserDocument).toPromise();
      return (response.data.currentUser as User) || null;
    } catch (error) {
      console.error(`currentUserFetch -> client.query() ERROR: \n${error}`);
      return null;
    }
  },
});

// set user data in the store
export const currentUserState = atom<User | null>({
  key: "currentUserState",
  default: currentUserFetch,
});
```

**Comment by hayes** [comment]
can you check to make sure your version of graphql is also up to date?

**Comment by hayes** [comment]
@felixhaeberle going to close this out, and assume it was an issue with the graphql version, if that wasn't the issue or you are still running into this problem let me know and I can re-open it

**Comment by felixhaeberle** [comment]
Sorry for not answering, it was indeed the graphql version!! 😊 Thanks 🙏
