### ISSUE TITLE
Getting `Cannot read properties of undefined (reading 'Symbol(Pothos.contextCache)')` for relatedConnection

### ISSUE THREAD

**Issue by villesau** [hayes/pothos#812]
I'm getting following error:

```
TypeError: Cannot read properties of undefined (reading 'Symbol(Pothos.contextCache)')
    at /Users/me/myproject/node_modules/@pothos/core/src/utils/context-cache.ts:20:67
    at cache (/Users/me/myproject/node_modules/@pothos/plugin-prisma/src/util/loader-map.ts:27:17)
    at Array.forEach (<anonymous>)
    at forEach (/Users/me/myproject/node_modules/@pothos/plugin-prisma/src/util/loader-map.ts:26:22)
    at queryFromInfo (/Users/me/myproject/node_modules/@pothos/plugin-prisma/src/util/map-query.ts:374:20)
    at resolve (/Users/me/myproject/node_modules/@pothos/plugin-prisma/src/field-builder.ts:37:34)
    at executeField (/Users/me/myproject/node_modules/graphql/execution/execute.js:481:20)
    at executeFields (/Users/me/myproject/node_modules/graphql/execution/execute.js:413:20)
    at executeOperation (/Users/me/myproject/node_modules/graphql/execution/execute.js:344:14)
    at execute (/Users/me/myproject/node_modules/graphql/exection/execute.js:136:20)
```

from the following kind of code:

```
export const RelatedObject = builder.prismaObject('related_objects', {
  name: 'RelatedObject',
  fields: t => ({
    id: t.exposeID('id')
  })
});

export const Object = builder.prismaObject('objects', {
  name: 'Object',
  interfaces: [SomeInterface],
  fields: t => ({
    id: t.exposeID('id'),
    relatedObjects: t.relatedConnection('related_objects', {
      type: RelatedObject,
      cursor: 'id'
    })
  })
});
```

while using following query:

```
      query GetRelatedObjects($objectId: ID!) {
        object(objectId: $objectId) {
          relatedObjects {
            pageInfo {
              hasNextPage
              endCursor
            }
            edges {
              node {
                id
              }
            }
          }
        }
      }
```

There are other fields as well and the code & schema are rather complex in overall, but this is the structure I'm roughly testing against. The query is exact.

**Comment by hayes** [comment]
I think this happens when you haven't generated your Prisma client, make sure you run Prisma generate after installing new dependencies

**Comment by villesau** [comment]
I just found the culprit: Prisma client is generated, but mistakenly I did not pass context in `contextValue` in tests.

```
    const response: any = await graphql({
      schema,
      source: gql,
      //contextValue: { // <-- this was missing
      //  variableInContext
     // },
      variableValues: {
        id
      }
    });
```

So not necessarily an issue in Pothos, although it would be nice if it would throw more helpful error when context is missing. I think that context might not be strictly required so in some very rare occasions this might be a problem. But likely a mistake in 99% of cases.

**Comment by Deadalusmask** [comment]
I got same error when using `graphql-http`, and resolved with adding `context` in `createHandler` args:
 ```ts
 import { createHandler } from 'graphql-http/lib/use/http'
 router.use(
  '/graphql',
  createHandler({
    schema,
    context: {}  // adding this line
  })
)
```

**Comment by hayes** [comment]
I'd strongly recommend creating a separate context object for each request.  The context object is used by some plugins as a cache for various things that you generally don't want to share between requests

**Comment by Deadalusmask** [comment]
I followed [Context object](https://pothos-graphql.dev/docs/guide/context#context-object)  docs and change it into a function to generate context for each request, thanks for reminding!
