### ISSUE TITLE
Cannot return null from nullable prisma connection resolver

### ISSUE THREAD

**Issue by knpwrs** [hayes/pothos#868]
When you return `null` from a `prismaConnection` field with `nullable` set to `true`:

```ts
  mySubscriptionUploadRecords: t.prismaConnection({
    type: 'UploadRecord',
    cursor: 'id',
    maxSize: 20,
    defaultSize: 20,
    nullable: true,
    resolve: async (query, _root, _args, context) => {
      return null;
    },
  }),
```

You get the following error:

```
ERR TypeError: Cannot read properties of null (reading 'length')
   at wrapConnectionResult (file:///home/node/app/node_modules/@pothos/plugin-prisma/src/util/cursors.ts:287:32)
   at resolvePrismaCursorConnection (file:///home/node/app/node_modules/@pothos/plugin-prisma/src/util/cursors.ts:338:8)
   at async Promise.all (index 0)
   at async promiseForObject (file:///home/node/app/node_modules/@graphql-tools/executor/esm/execution/promiseForObject.js:11:28)
   at async file:///home/node/app/node_modules/@envelop/core/esm/orchestrator.js:373:27
   at async YogaServer.getResultForParams (file:///home/node/app/node_modules/graphql-yoga/esm/server.js:324:26)
   at async YogaServer.handle (file:///home/node/app/node_modules/graphql-yoga/esm/server.js:74:29)
   at async handlerWithErrorHandling (file:///home/node/app/node_modules/@whatwg-node/server/index.mjs:631:38)
   at async handleRequest (file:///home/node/app/node_modules/@whatwg-node/server/index.mjs:306:24)
   at async Object.handler (file:///home/node/app/src/server.ts:26:22)  {
```

Returning an `empty` array _does_ work, but this is not semantically the same as returning `null`.

**Comment by hayes** [comment]
Looks like this just needs a null check here: https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/util/cursors.ts#L330

Should be an easy fix

**Comment by hayes** [comment]
Just pushed a fix, should be released in a few minutes!
