### ISSUE TITLE
PothosSchemaError: Ref Query has not been implemented

### ISSUE THREAD

**Issue by hari4698** [hayes/pothos#878]
I'm using Prisma as the ORM and @pothos/plugin-prisma as the plugin. When I start the graphql-yoga server, I get the error below.

```
file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/config-store.ts:391
    }
     ^
PothosSchemaError: Ref Query has not been implemented
    at ConfigStore.onTypeConfig (file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/config-store.ts:391:6)
    at cb (file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/config-store.ts:474:3)
    at pendingActions (file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/config-store.ts:446:32)
    at Array.forEach (<anonymous>)
    at ConfigStore.typeConfigs [as prepareForBuild] (file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/config-store.ts:446:12)
    at BuildCache.builtTypes [as buildAll] (file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/build-cache.ts:172:22)
    at SchemaBuilder.toSchema (file:///C:/Users/user/Documents/Projects/project1/node_modules/@pothos/core/src/builder.ts:597:11)
    at file:///C:/Users/user/Documents/Projects/project1/server/schema.ts:5:31
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
[nodemon] app crashed - waiting for file changes before starting...
```

Creating this as an issue because the error seems to be coming from the `config-store.ts` file inside the package. 

## Supporting code: 

`builder.ts`

```typescript
import PrismaPlugin from "@pothos/plugin-prisma";
import type PrismaTypes from '@pothos/plugin-prisma/generated';
import { prisma } from "./db.js";
import SchemaBuilder from "@pothos/core";
import {DateResolver} from "graphql-scalars";

export const builder = new SchemaBuilder<{
    Scalars: {
        Date: { Input: Date; Output: Date };
    };
    PrismaTypes: PrismaTypes;
}>({
    plugins: [PrismaPlugin],
    prisma: {
        client: prisma,
    },
});

builder.addScalarType("Date",DateResolver,{});
```

`schema.ts`

```typescript
import { builder } from "./builder.js";
import "./models/Job.js";
import "./models/JobCostCode.js";

export const schema = builder.toSchema({});
```
`index.ts`

```typescript
import { createYoga } from 'graphql-yoga'
import { createServer } from 'node:http'
import { schema } from "./schema.js";

const yoga = createYoga({ schema });

const server = createServer(yoga);

server.listen(4000, () => {
    console.log(' 🚀 Server is running on http://localhost:4000');
});
```

**Comment by hayes** [comment]
Have you implemented the Query type somewhere? (`builder.queryType({})`)

**Comment by hari4698** [comment]
I have implemented `queryField` in my models but not `queryType`. I'm following the tutorial from [Prisma](https://www.prisma.io/blog/e2e-type-safety-graphql-react-3-fbV2ZVIGWg#implement-your-queries)

`Job.ts`

```typescript
import { builder } from "../builder.js";
import { prisma } from "../db.js";

builder.prismaObject("heavyjob_jm_job", {
    fields: (t) => ({
        id: t.exposeID("ID"),
        businessUnitCode: t.exposeString("BusinessUnitCode"),
        businessUnitDescription: t.exposeString("BusinessUnitDescription")
    })
});

builder.queryField("jobs", (t) => 
    t.prismaField({
        type: ["heavyjob_jm_job"],
        resolve: async (query, args, ctx) => {
            return await prisma.heavyjob_jm_job.findMany({...query});
        }
    }))
```

**Comment by hayes** [comment]
You need to add the definition for the query type as shown above
