### ISSUE TITLE
Unknown Type Error with Subgraph and Federation Plugins

### ISSUE THREAD

**Issue by arimgibson** [hayes/pothos#884]
When using the Subgraph and Federation plugins together, this error occurs when trying to compile a subgraph schema:
```
/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/error.ts:36
  err: (message: string, options?: GraphQLErrorOptions) => new GraphQLError(
                                                           ^
GraphQLError: Unknown type CreateUserOutputPayload
    at Object.err (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/error.ts:36:60)
    at getReferencedType (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/buildSchema.ts:293:34)
    at buildTypeReferenceFromAST (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/buildSchema.ts:524:14)
    at buildTypeReferenceFromAST (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/buildSchema.ts:518:23)
    at buildFieldDefinitionInner (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/buildSchema.ts:481:16)
    at buildNamedTypeInner (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/buildSchema.ts:403:9)
    at buildSchemaFromAST (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/buildSchema.ts:158:5)
    at buildSubgraph (/home/redacted/node_modules/.pnpm/@apollo+federation-internals@2.4.2_graphql@16.6.0/node_modules/@apollo/federation-internals/src/federation.ts:1250:27)
    at printSubgraphSchema (/home/redacted/node_modules/.pnpm/@apollo+subgraph@2.4.2_graphql@16.6.0/node_modules/@apollo/subgraph/src/printSubgraphSchema.ts:16:33)
    at SchemaBuilder.toSubGraphSchema (/home/redacted/node_modules/.pnpm/@pothos+plugin-federation@3.10.0_@apollo+subgraph@2.4.2_graphql@16.6.0/node_modules/@pothos/plugin-federation/src/schema-builder.ts:142:34) {
  path: undefined,
  locations: undefined,
  extensions: { code: 'INVALID_GRAPHQL' }
}
```

A simple fix is to ensure that the Federation and Directives plugins are before the SubGraph plugin in the SchemaBuilder:
```
import DirectivePlugin from '@pothos/plugin-directives';
import FederationPlugin from '@pothos/plugin-federation';
import SubGraphPlugin from '@pothos/plugin-sub-graph';
const builder = new SchemaBuilder({
  plugins: [DirectivePlugin, FederationPlugin, SubGraphPlugin],
});
```

This issue is likely due to how the separate plugins are loaded and process the subgraph. Happy to PR a note about plugin ordering to the docs if that's the only issue here; let me know any other information useful for debugging. I can include a reproduction but thought it might be overkill as this issue seems fairly minor.

**Comment by hayes** [comment]
Any chance you could provide a slightly more complete reproduction here. I've tried to reproduce the issue here and have not been able to.  It's likely that there is some sort of implicit plugin ordering dependency here, but I haven't been able to identify what it might be based on this error so far.  The error you shared looks like it references a type created by the relay plugin which may also be a factor, but it's hard to tell.

**Comment by arimgibson** [comment]
Yep, will do! Good to know that the Relay plugin might play a role; I'll try to grab some more errors first and then can create a repro example as well

**Comment by arimgibson** [comment]
I wasn't able to replicate either; might be due to a very specific configuration inside the codebase I was working on since it might be due to the interactions of 4 separate plugins together. Am going to close as not planned, and hopefully this issue and that fix might help someone in the future :shrug:
