### ISSUE TITLE
[@pothos/plugin-prisma] Cannot read properties of undefined with Prisma 4.14.0

### ISSUE THREAD

**Issue by joshuaavalon** [hayes/pothos#907]
* @pothos/plugin-prisma: 3.50.1
* prisma: 4.14.0

> file:///C:/Users/user/project/git/api/node_modules/@pothos/plugin-prisma/esm/util/datamodel.js:34
    const modelData = dmmf.datamodel.models.find((model) => model.name === name);
                           ^
> TypeError: Cannot read properties of undefined (reading 'datamodel')
    at getModel (file:///C:/Users/user/project/git/api/node_modules/@pothos/plugin-prisma/esm/util/datamodel.js:34:28)
    at getDefaultIDSerializer (file:///C:/Users/user/project/git/api/node_modules/@pothos/plugin-prisma/esm/util/cursors.js:87:19)
    at SchemaBuilder.prismaNode (file:///C:/Users/user/project/git/api/node_modules/@pothos/plugin-prisma/esm/schema-builder.js:44:81)

I can confirm it works with prisma 4.13.0

**Comment by hayes** [comment]
This is the PR that broke things: https://github.com/prisma/prisma/pull/18861, not sure yet what the fix in Pothos will look like

**Comment by hayes** [comment]
Should be fixed in the latest version
